package icedice;

import java.io.*;

import icedice.players.*;
import icedice.content.*;
import icedice.*;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Iceframe.java
 *
 * Created on 20-Jul-2010, 04:23:27
 */

/**
 * @author Kieran Anderson
 */
public class Iceframe extends javax.swing.JFrame {

    /**
     * Creates new form Iceframe
     */
    public Iceframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commandText = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        commandList = new javax.swing.JComboBox();
        sendCommand = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IceyyScape Control Pannel");


        username.setText("Icedice");

        commandList.setModel(new javax.swing.DefaultComboBoxModel(Engine.consoleCommand.commandList));

        sendCommand.setText("Send Command");
        sendCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendCommandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(commandText, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sendCommand))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(commandList, 0, 285, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(commandList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(commandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sendCommand, 0, 0, Short.MAX_VALUE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendCommandActionPerformed
        String command = this.commandList.getSelectedItem().toString();
        String text = this.commandText.getText();
        if (Engine.consoleCommand.isCommand(command)) {
            Engine.consoleCommand.username = this.username.getText();
            Engine.consoleCommand.handleCommand(command + " " + text);
        }
        this.commandText.setText("");
    }//GEN-LAST:event_sendCommandActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iceframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox commandList;
    private javax.swing.JTextField commandText;
    private javax.swing.JButton sendCommand;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
